version: "3"
services:
  openresty:
    container_name: api-gateway
    build: .
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:6.1.1
    ports:
      - "9600:9600"
    volumes:
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline
      - ./elk/logstash/settings:/usr/share/logstash/config
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.1.1
    ports:
      - "5601:89"
    links:
      - elasticsearch
volumes:
  es-data:

