version: "3"
services:

  openresty:
    container_name: api-gateway
    build: .
    labels:
      containerName: api-gateway
    ports:
      - "8000:80"
    external_links:
      - logstash:logstash
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./lua:/usr/local/openresty/nginx/lua
      - ./sample.nginx:/usr/local/openresty/nginx/conf/nginx.conf
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:5000"
        tag: "{{.Name}}"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-dev:/usr/share/elasticsearch/data

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:6.1.1
    ports:
      - "9600:9600"
      - "5000:5000/udp"
    links:
      - elasticsearch
    volumes:
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./elk/logstash/settings:/usr/share/logstash/config:ro

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.1.1
    ports:
      - "5601:5601"
    links:
      - elasticsearch

volumes:
  es-data-dev: