version: "3"
services:
  openresty:
    container_name: api-gateway
    build: .
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./openresty/lua:/usr/local/openresty/nginx/lua
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/nginx.conf
    depends_on:
      - redis
    networks:
      - api_gateway
  redis:
    container_name: redis
    image: redis:4.0.2-alpine
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      api_gateway:
        aliases:
          - redis
networks:
  api_gateway: