version: "3"
services:
  openresty:
    container_name: api-gateway
    build: .
    ports:
      - "8000:80"
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:3.2.8-alpine
    expose: 
      - "6379"